AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Spring Boot app in Docker on EC2

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair Name
  DockerImage:
    Type: String
    Description: Full Docker Image Name (e.g., vishaltech123/demo:latest)
  DockerHubToken:
    Type: String
    NoEcho: true
    Description: Docker Hub Access Token (use --password-stdin)

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to app and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8081
          ToPort: 8081
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 AMI (us-east-1)
      SecurityGroups: [!Ref MySecurityGroup]
      UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install docker -y
            service docker start
            systemctl enable docker
            usermod -aG docker ec2-user
            docker login -u vishaltech123 -p Career@123#
            docker pull vishaltech123/demo:latest
            docker run -d -p 8081:8080 vishaltech123/demo:latest

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MyInstance.PublicIp
